### ISSUE TITLE
Session message limits / renegotiation

### ISSUE THREAD

**Issue by lann** [lithdew/monte#2]
Though I haven't carefully analyzed the entire code base, it doesn't appear that there is any mitigation for overflowing the GCM counter in a session. At the claimed 1500MiB/s throughput some workloads could blow through GCM's 32-bit counter leading to AES nonce reuse, which is _very bad_.

**Comment by lithdew** [comment]
In no way am I a cryptographer, though I would love some further insight on this: right now the nonce is a 64-bit unsigned integer that is incremented, zero-padded with bytes s.t. it is actually 12 bytes (96 bits).

Reaching 1500MiB/s comprised of sending 1400 bytes per frame, which implies sending 1,123,474 encrypted frames per second which comprise 1,123,474 counter increments per second. Quick back-of-the-hand math, it would take 520,655 years for there to be an overflow given that the nonce counter is represented as an unsigned 64-bit integer.

Is there a glaring internal 32-bit counter over GCM that I'm missing here?

**Comment by lann** [comment]
No, this was my misunderstanding of how Go's GCM impl works. Sorry about that!

**Comment by lann** [comment]
As an aside, since `SessionConn` is exported, you may want to note that it must never be used twice with the same key.

**Comment by lann** [comment]
...which also means that a `Session` shouldn't be reused.
