### ISSUE TITLE
Improve Session misuse resistance

### ISSUE THREAD

**Issue by lann** [lithdew/monte#3]
Me again! Hopefully I'm actually correct this time...

Since `SessionConn` always uses a counter starting at 1 for its GCM nonce, it must never be used with the same encryption key twice. Consider at least documenting this constraint, or if possible don't export `SessionConn` at all.

Similarly, a single `Session` must never be reused to connect to the same peer `Session` twice (since it would then generate the same shared key, violating the requirement above). Here I believe there is a simple fix: move the key generation from `NewSession` to `Establish`; as a bonus, you then don't even need to store `ourPriv` on `Session`.

Take a look at https://noiseprotocol.org/noise.html (especially section 14).

**Comment by lithdew** [comment]
Good points! I'll be sure to document the constraint and look into moving the key generation over to `Establish` tomorrow; thank you :smile:.

**Comment by lithdew** [comment]
Moved key generation from `NewSession` to `DoServer` and `DoClient`, and documented the constraint that the same `cipher.AEAD` suite should not be used for multiple `SessionConn`'s.

Let me know what you think.
